import { ParsedYahooMedia } from '../types';

export const SAMPLE_YAHOO_ITEMS: ParsedYahooMedia[] = [
  {
    id: 'syo_sample_01',
    url: 'https://news.yahoo.com/trump-posts-trump-strait-map-iran-offers-reopen-hormuz-142010892.html',
    title: 'Trump Posts "Trump Strait" Map After Iran Offers to Reopen Hormuz Within 7 Days',
    description: 'Associated Press geopolitical analysis detailing the latest international shipping transit discussions in the Persian Gulf and diplomatic negotiations regarding the Strait of Hormuz.',
    author: 'Associated Press & Yahoo News Editorial',
    publishedDate: 'March 24, 2026',
    thumbnailUrl: '/media/news_strait.jpg',
    category: 'News',
    primaryType: 'video',
    duration: '03:42',
    previewVideoUrl: '/media/news_strait.mp4',
    previewAudioUrl: '/media/news_strait.mp3',
    videoStreams: [
      { quality: '1080p', resolution: '1920x1080', format: 'mp4', filesize: '48.2 MB', bitrate: '3200 kbps', fps: 60, hasAudio: true },
      { quality: '720p', resolution: '1280x720', format: 'mp4', filesize: '26.8 MB', bitrate: '1800 kbps', fps: 30, hasAudio: true },
      { quality: '480p', resolution: '854x480', format: 'mp4', filesize: '14.1 MB', bitrate: '950 kbps', fps: 30, hasAudio: true },
      { quality: '360p', resolution: '640x360', format: 'mp4', filesize: '8.4 MB', bitrate: '600 kbps', fps: 30, hasAudio: true },
    ],
    audioStreams: [
      { quality: '320kbps', format: 'mp3', filesize: '8.6 MB', sampleRate: '48 kHz', codec: 'LAME MP3 Ultra' },
      { quality: '192kbps', format: 'mp3', filesize: '5.2 MB', sampleRate: '44.1 kHz', codec: 'LAME MP3 High' },
      { quality: '128kbps', format: 'm4a', filesize: '3.4 MB', sampleRate: '44.1 kHz', codec: 'AAC-LC' },
    ],
    blogExports: [
      { format: 'markdown', label: 'Markdown Document (.md)', description: 'Clean formatted markdown with citations & headers', filesize: '12 KB', readerOptimized: true },
      { format: 'pdf', label: 'Printable Reader PDF', description: 'Formatted for print or offline tablet reading', filesize: '145 KB', readerOptimized: true },
      { format: 'html', label: 'Clean HTML Reader', description: 'Standalone offline HTML without Yahoo tracker scripts', filesize: '24 KB', readerOptimized: true },
      { format: 'txt', label: 'Plain Text (.txt)', description: 'Unformatted plain text for research notes', filesize: '8 KB', readerOptimized: false },
    ],
    blogContent: {
      summary: 'High-level diplomatic developments and maritime navigation advisories following recent regional communications regarding commercial shipping routes in the Gulf.',
      headings: ['Background of the Maritime Dispute', 'Strategic Implications for Oil Transits', 'Allied Coalition Reactions'],
      paragraphs: [
        'Following several days of intensified regional dialogue, officials today addressed international maritime corridors during a high-profile press briefing.',
        'Commercial shipping insurers have reportedly updated route safety classifications, with several major logistics carriers assessing transit viability across commercial routes.',
        'Energy analysts noted that sustained stability across the waterway remains critical for global crude distribution, with spot prices responding rapidly to official announcements.',
      ],
      keyPoints: [
        'International trade route security reassessed by global shipping authorities.',
        'Strategic diplomatic exchanges underway between maritime security bodies.',
        'Energy supply chain impact monitored closely by financial markets.',
      ],
    },
  },
  {
    id: 'syo_sample_02',
    url: 'https://finance.yahoo.com/news/sp500-tech-earnings-surge-ai-semiconductors-rally-164500112.html',
    title: 'S&P 500 Climbs to 7,743 as Semiconductor Rally Fuels Major Market Breakthrough',
    description: 'Yahoo Finance Market Brief: Deep dive into the latest macroeconomic indicators, quarterly semiconductor margins, and institutional liquidity flows driving equity indexes.',
    author: 'Yahoo Finance Intelligence & Market Desk',
    publishedDate: 'March 25, 2026',
    thumbnailUrl: '/media/finance_sp500.jpg',
    category: 'Finance',
    primaryType: 'video',
    duration: '06:15',
    previewVideoUrl: '/media/finance_sp500.mp4',
    previewAudioUrl: '/media/finance_sp500.mp3',
    videoStreams: [
      { quality: '1080p', resolution: '1920x1080', format: 'mp4', filesize: '82.4 MB', bitrate: '3400 kbps', fps: 60, hasAudio: true },
      { quality: '720p', resolution: '1280x720', format: 'mp4', filesize: '44.1 MB', bitrate: '1900 kbps', fps: 30, hasAudio: true },
      { quality: '480p', resolution: '854x480', format: 'mp4', filesize: '22.0 MB', bitrate: '1000 kbps', fps: 30, hasAudio: true },
    ],
    audioStreams: [
      { quality: '320kbps', format: 'mp3', filesize: '14.4 MB', sampleRate: '48 kHz', codec: 'LAME MP3 Ultra' },
      { quality: '192kbps', format: 'mp3', filesize: '8.6 MB', sampleRate: '44.1 kHz', codec: 'LAME MP3 High' },
      { quality: '128kbps', format: 'm4a', filesize: '5.8 MB', sampleRate: '44.1 kHz', codec: 'AAC-LC' },
    ],
    blogExports: [
      { format: 'markdown', label: 'Market Report (.md)', description: 'Tabulated earnings data, ticker metrics and analyst commentary', filesize: '16 KB', readerOptimized: true },
      { format: 'pdf', label: 'Executive PDF Brief', description: 'Financial summary with sector allocation tables', filesize: '210 KB', readerOptimized: true },
      { format: 'html', label: 'Interactive HTML Brief', description: 'Stand-alone financial digest for offline archival', filesize: '32 KB', readerOptimized: true },
    ],
    blogContent: {
      summary: 'Tech bellwethers led a broad-based equities rally today, pushing benchmark indexes into uncharted territory on unprecedented infrastructure investment numbers.',
      headings: ['Semiconductor Capital Expenditure Accelerates', 'Treasury Yield Dynamics and Dollar Valuation', 'Upcoming Federal Reserve Projections'],
      paragraphs: [
        'Wall Street pushed into record territory this afternoon, driven by blowout quarterly guidance from major semiconductor foundries and data center suppliers.',
        'Market breadth expanded noticeably beyond mega-cap hardware leaders into industrial automation and electrical grid infrastructure providers.',
        'Trading desks reported aggressive institutional accumulation across software platforms leveraging next-generation agentic workflows.',
      ],
      keyPoints: [
        'Benchmark S&P 500 registers another all-time session record.',
        'Hardware infrastructure capex projections increased by 18% year-over-year.',
        'Analyst consensus remains cautiously optimistic heading into consumer spending reports.',
      ],
    },
  },
  {
    id: 'syo_sample_03',
    url: 'https://sports.yahoo.com/stephen-curry-caitlin-clark-three-point-showdown-highlights-210000451.html',
    title: 'Stephen Curry and Caitlin Clark Set Historic All-Star 3-Point Exhibition Records',
    description: 'Yahoo Sports Spotlight: Complete breakdown of the record-breaking long-range shooting duel, player post-game reactions, and shooting stroke mechanical analysis.',
    author: 'Yahoo Sports Basketball Analysis Team',
    publishedDate: 'March 23, 2026',
    thumbnailUrl: '/media/sports_championship.jpg',
    category: 'Sports',
    primaryType: 'video',
    duration: '04:55',
    previewVideoUrl: '/media/sports_championship.mp4',
    previewAudioUrl: '/media/sports_championship.mp3',
    videoStreams: [
      { quality: '1080p', resolution: '1920x1080', format: 'mp4', filesize: '64.5 MB', bitrate: '3600 kbps', fps: 60, hasAudio: true },
      { quality: '720p', resolution: '1280x720', format: 'mp4', filesize: '35.2 MB', bitrate: '2000 kbps', fps: 60, hasAudio: true },
      { quality: '480p', resolution: '854x480', format: 'mp4', filesize: '18.9 MB', bitrate: '1100 kbps', fps: 30, hasAudio: true },
    ],
    audioStreams: [
      { quality: '320kbps', format: 'mp3', filesize: '11.3 MB', sampleRate: '48 kHz', codec: 'LAME MP3 Studio' },
      { quality: '192kbps', format: 'mp3', filesize: '6.8 MB', sampleRate: '44.1 kHz', codec: 'LAME MP3 High' },
    ],
    blogExports: [
      { format: 'markdown', label: 'Sports Recap (.md)', description: 'Play-by-play shot tracker and post-game quotes', filesize: '9 KB', readerOptimized: true },
      { format: 'pdf', label: 'Sports Edition PDF', description: 'Clean printable box score and photo recap', filesize: '180 KB', readerOptimized: true },
    ],
    blogContent: {
      summary: 'The historic co-ed shooting competition produced thrilling consecutive 29-point rounds, captivating fans worldwide with flawless perimeter shooting.',
      headings: ['Round 1: Rapid Release Mechanics', 'The Money Ball Rack Climax', 'Post-Game Reflections & Legacy'],
      paragraphs: [
        'Before a sold-out arena and millions watching globally, the two most influential shooters of their generations traded clutch shots in a historic duel.',
        'Both shooters converted over 78% of their perimeter attempts, including unanimous makes from the deep 30-foot perimeter marks.',
      ],
      keyPoints: [
        'Combined score of 58 points across two rounds.',
        'Deep range consistency analyzed with shot-tracking metrics.',
      ],
    },
  },
  {
    id: 'syo_sample_04',
    url: 'https://www.yahoo.com/lifestyle/8-genius-tips-to-save-money-on-groceries-130000889.html',
    title: '8 genius tips to save money on groceries',
    description: 'Verified Yahoo Lifestyle & Problem Solved stream: If you\'re looking to spend a little less at the grocery store, here are 8 smart shopping tips, pantry strategies, and unit-price hacks.',
    author: 'Problem Solved · Yahoo Life',
    publishedDate: 'Recently Published',
    thumbnailUrl: '/media/lifestyle_groceries.jpg',
    category: 'Lifestyle',
    primaryType: 'video',
    duration: '01:20',
    readTime: '4 min read',
    previewVideoUrl: '/media/lifestyle_groceries.mp4',
    previewAudioUrl: '/media/lifestyle_groceries.mp3',
    videoStreams: [
      { quality: '1080p', resolution: '1920x1080', format: 'mp4', filesize: '56.4 MB', bitrate: '3200 kbps', fps: 60, hasAudio: true },
      { quality: '720p', resolution: '1280x720', format: 'mp4', filesize: '29.8 MB', bitrate: '1800 kbps', fps: 30, hasAudio: true },
      { quality: '480p', resolution: '854x480', format: 'mp4', filesize: '15.6 MB', bitrate: '900 kbps', fps: 30, hasAudio: true },
    ],
    audioStreams: [
      { quality: '320kbps', format: 'mp3', filesize: '9.8 MB', sampleRate: '48 kHz', codec: 'LAME MP3 Studio' },
      { quality: '192kbps', format: 'mp3', filesize: '6.2 MB', sampleRate: '44.1 kHz', codec: 'LAME MP3 Voice Reader' },
    ],
    blogExports: [
      { format: 'markdown', label: 'Grocery Savings Guide (.md)', description: 'Itemized grocery hacks, price comparison matrix and seasonal calendar', filesize: '14 KB', readerOptimized: true },
      { format: 'pdf', label: 'Culinary Budget PDF', description: 'Clean printable kitchen pantry shopping checklist', filesize: '195 KB', readerOptimized: true },
      { format: 'html', label: 'Ad-Free Reader HTML', description: 'Single-file offline article reader without banners', filesize: '28 KB', readerOptimized: true },
      { format: 'txt', label: 'Text Shopping List (.txt)', description: 'Quick itemized list for mobile notes', filesize: '4 KB', readerOptimized: false },
    ],
    blogContent: {
      summary: 'Actionable grocery store hacks from Problem Solved to cut household food spending without sacrificing nutritional variety or family favorite meals.',
      headings: ['1. Shop Your Pantry First', '2. Unit Pricing & Store Brands', '3. Frozen Produce Equals Fresh', '4. Stick to the Perimeter'],
      paragraphs: [
        'If you\'re looking to spend a little less at the grocery store, start by shopping your pantry and fridge before making your weekly list.',
        'Always check the unit price (price per ounce or pound) on store shelves rather than the prominent sticker price to reveal hidden discounts.',
        'Frozen fruits and vegetables offer identical nutritional value to fresh produce while eliminating costly spoilage and food waste.',
      ],
      keyPoints: [
        '8 actionable shopping tips verified by food economists.',
        'Average household saves $280-$350 monthly with planned grocery lists.',
        'Store brand substitutions yield 25% savings without taste compromises.',
      ],
    },
  },
  {
    id: 'syo_sample_05',
    url: 'https://tech.yahoo.com/bill-gates-warns-ai-is-powerful-enough-to-drive-events-cause-a-billion-surprises-111500334.html',
    title: 'Bill Gates: Next-Generation Autonomous AI Systems Will Reshape Global Science and Software',
    description: 'Yahoo Tech In-Depth: Exclusive commentary on software engineering automation, biotech drug discoveries, and computational modeling breakthroughs.',
    author: 'Yahoo Tech & Business Insider Syndicate',
    publishedDate: 'March 20, 2026',
    thumbnailUrl: '/media/tech_review.jpg',
    category: 'Tech',
    primaryType: 'video',
    duration: '08:40',
    readTime: '8 min read',
    previewVideoUrl: '/media/tech_review.mp4',
    previewAudioUrl: '/media/tech_review.mp3',
    videoStreams: [
      { quality: '1080p', resolution: '1920x1080', format: 'mp4', filesize: '112.5 MB', bitrate: '3500 kbps', fps: 60, hasAudio: true },
      { quality: '720p', resolution: '1280x720', format: 'mp4', filesize: '58.0 MB', bitrate: '1800 kbps', fps: 30, hasAudio: true },
      { quality: '480p', resolution: '854x480', format: 'mp4', filesize: '32.1 MB', bitrate: '900 kbps', fps: 30, hasAudio: true },
    ],
    audioStreams: [
      { quality: '320kbps', format: 'mp3', filesize: '19.8 MB', sampleRate: '48 kHz', codec: 'LAME MP3 Studio' },
      { quality: '192kbps', format: 'mp3', filesize: '11.5 MB', sampleRate: '44.1 kHz', codec: 'LAME MP3 High' },
    ],
    blogExports: [
      { format: 'markdown', label: 'Tech Analysis Document (.md)', description: 'Full transcript with technical benchmarks & diagrams', filesize: '18 KB', readerOptimized: true },
      { format: 'pdf', label: 'AI Whitepaper PDF', description: 'Academic reader view suitable for archiving', filesize: '240 KB', readerOptimized: true },
    ],
    blogContent: {
      summary: 'In an expansive keynote conversation, Bill Gates outlined how generative logic models are advancing from assistive chatbots to foundational scientific problem solvers.',
      headings: ['The Evolution from Assistants to Reasoning Engines', 'Accelerating Protein Folding and Material Science', 'Workforce Adaptability and Global Productivity'],
      paragraphs: [
        'Speaking to technologists and university researchers, Gates characterized the present technological transition as more profound than the personal computing revolution of the late twentieth century.',
        'Rather than merely synthesizing existing written text, upcoming systems are validating novel chemical compounds and simulating complex climatic models in hours instead of decades.',
      ],
      keyPoints: [
        'Multimodal reasoning agents deployed across pharmaceutical research pipelines.',
        'Open-access foundation models accelerating mathematical hypothesis verification.',
      ],
    },
  },
];
